### ISSUE TITLE
login issue!!!

### ISSUE THREAD

**Issue by bakhtawar12** [bakhtawar12/grocery-panda#1]
should we add phone number in login or  it is ok with  username and pasword only???
need suggestion!

**Comment by bakhtawar12** [comment]
i think its not necessary to ask about phone number its a registration demand..!!!
DR.ANAND MISHRA.

**Comment by zoha428** [comment]
product class contains add and delete of the stock ikr?

**Comment by bakhtawar12** [comment]
g

**Comment by bakhtawar12** [comment]
finally done with our registration and login task
